;
; File generated by cc65 v 2.19 - Git 30b00ed
;
	.fopt		compiler,"cc65 v 2.19 - Git 30b00ed"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_num
	.export		_main

.segment	"BSS"

_num:
	.res	2,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     #$00
	lda     #$9F
	sta     _num
	stx     _num+1
	lda     _num
	ldx     _num+1
	jsr     shlax1
	sta     _num
	stx     _num+1
	ldx     #$00
	lda     #$00
	jmp     L0001
L0001:	rts

.endproc

